### ISSUE TITLE
Improve mobile view of website

### ISSUE THREAD

**Issue by R1D3R175** [Bonfra04/Stronzflix#14]
![Screenshot_20240819_135430_Chrome.jpg](https://github.com/user-attachments/assets/4fb60f3b-1e2f-47bb-8ec7-81839938e5e4)

- Implement drawer in place of existing navbar (or just remove it all together since they don't link to new pages)
- Make buttons bigger (thus their text size)

**Comment by R1D3R175** [comment]
This is unrelated, but have you considered the idea of automatically choosing the file for the user based on their User-Agent?

**Comment by Bonfra04** [comment]
Closed by #27
