### ISSUE TITLE
Increase text length for cards search result

### ISSUE THREAD

**Issue by R1D3R175** [Bonfra04/Stronzflix#18]
When there is a TV show with multiple seasons (or an anime, i.e. take Kengan Ashura as an edge case) you can't really distinguish which is what. 
An idea could be to decrease font size by 1-2px and add a secondary row; or just remove the border altogether and place the text on top of the image with a light box shadow to have some contrast (take Aniyomi for example)

**Comment by Bonfra04** [comment]
Fixed in 3da6696ec7320da8dfb61bb7db1be38eebc98029.
