### ISSUE TITLE
Add player QoL controls

### ISSUE THREAD

**Issue by R1D3R175** [Bonfra04/Stronzflix#20]
While the player has the main features implement, it lacks many of the features a normal user is accustomed to.

Here's a list of essential feature a player should implement:
- Double tap on left/right half on the screen should decrement/increment the current time by some fixed amount of seconds (e.g. 10 seconds)
- Sliding down/up on left side of the screen should decrease/increase the brightness of the screen
- Sliding down/up on right side of the screen should decrease/increase volume (this doesn't mean that the volume control of the player shouldn't be there)
- Sliding left/right on any part of the video should make the user able to seek (i.e. VLC player)

Here's how I'll modify the existing features:
- Move the next episode button to the right of the play button at the center of the screen
- Add the previous episode button to the right of the play button at the center of the screen 
- Remove the play button on the bottom left of the screen since only desktop user expect it to be there
- Previous point also applies to previous/next episode buttons; mobile users expect it on the center of the screen and desktop users below the seek bar
- Make the volume controllable and not just an off/on switch (i.e. on click & hold make a slider appear, for example)

**Comment by Bonfra04** [comment]
> Double tap on left/right half on the screen should decrement/increment the current time by some fixed amount of seconds

Done in StronzLabs/StronzVideoPlayer@d32349c2ffdd2cada4e40ea5043a589449945236

> Sliding down/up on left side of the screen should decrease/increase the brightness of the screen

this will not be handled by the StronzVideoPlayer, the system settings of the host device will do

> Sliding down/up on right side of the screen should decrease/increase volume (this doesn't mean that the volume control of the player shouldn't be there)

this will not be handled by the StronzVideoPlayer, the hardware buttons on th host device will do

> Sliding left/right on any part of the video should make the user able to seek

I don't think i quite understood this one. Could you elaborate more? maybe with a demo video or something?

> Move the next episode button to the right of the play button at the center of the screen

Nah

> Add the previous episode button to the right of the play button at the center of the screen

Please open a different PR on the correct repo as this influences no only the mobile controls but its a feature for all platforms.

> Remove the play button on the bottom left of the screen since only desktop user expect it to be there

Nah

> Previous point also applies to previous/next episode buttons; mobile users expect it on the center of the screen and desktop users below the seek bar

Nah

> Make the volume controllable and not just an off/on switch (i.e. on click & hold make a slider appear, for example)

Hardware keys will do fine
