### ISSUE TITLE
Add "To Watch" section

### ISSUE THREAD

**Issue by R1D3R175** [Bonfra04/Stronzflix#26]
Currently there's no way to mark a certain show in a certain source to be watched later (similar to "Add To My List" on Netflix, for example). Would be a nice feature to have. This would also add more stuff to the homepage, making it less empty.

**Comment by Bonfra04** [comment]
This option is already available through the top right icon on the title page.
![image](https://github.com/user-attachments/assets/2c7cf384-f1ee-49ee-9e82-2e644283ba55)
![image](https://github.com/user-attachments/assets/c1e5c443-cc8c-4d8a-a843-282051860fc2)
