### ISSUE TITLE
Show episode number in the thumbnail

### ISSUE THREAD

**Issue by codesimo** [Bonfra04/Stronzflix#32]
It is not possible to know the episode number from the episode list at the moment.
Currently:
![image](https://github.com/user-attachments/assets/bfa99c7c-3d99-4f85-8dc4-9d2a00b3577e)

As should be (inspired by other sources):
![image](https://github.com/user-attachments/assets/443519e3-ca1c-4208-a679-c681272c70e2)

Also, it might make sense to add the episode and season number within the title while watching an episode

**Comment by Bonfra04** [comment]
> Also, it might make sense to add the episode and season number within the title while watching an episode

Please open another issue for this one

**Comment by Bonfra04** [comment]
Fixed in 12ed329
