### ISSUE TITLE
Going back to 00:00 doesn't work sometimes

### ISSUE THREAD

**Issue by codesimo** [Bonfra04/Stronzflix#34]
In this example it jumped ahead of 4 seconds, but on the same video it also jumped ahead of 24 seconds. Bojack Horseman S2:E6, but the content seems unrelated.

![Stronzflix_4lW282ecd7](https://github.com/user-attachments/assets/e3719eeb-df6d-4f15-bbd2-5260bb2befb0)

**Comment by Bonfra04** [comment]
Should be fixed by StronzLabs/StronzVideoPlayer@d8024899181b119fdf6db8111efe126807b06437.
It's hard to reproduce but the reference you gave seems to work fine. I'm closing this for the moment but feel free to reopen it if needed.
