### ISSUE TITLE
Chromecast icon disappears randomly

### ISSUE THREAD

**Issue by codesimo** [Bonfra04/Stronzflix#36]
![Stronzflix_66q5V1Ho6X](https://github.com/user-attachments/assets/c24c8a7e-13ce-430c-98c5-6592b54a1824)

Steps description:
1. Play something
2. Press the Chromecast icon
3. Press anywhere else on the screen

It seems to disappear for around 5 seconds.

**Comment by Bonfra04** [comment]
This will be fixed by moving the cast button outside the video player

**Comment by Bonfra04** [comment]
closed in 2ddc8b8a47d7f43aa4947b4aeac5230e5cf7fd33
