### ISSUE TITLE
Show something to tell the user that the file is being downloaded

### ISSUE THREAD

**Issue by R1D3R175** [Bonfra04/Stronzflix#39]
This issue is to be considered existing after #27 is merged.

Since downloads are being handled by JavaScript the browser doesn't (obviously) show anything.

Here's how we could implement some progress bar ourselves: https://stackoverflow.com/a/72903731/14508616

**Comment by Bonfra04** [comment]
Downloads handled in javascript as implemented in #27 were buggy and were reverted to being handled by the browser.
