### ISSUE TITLE
Deleted watched episode still reflects in "Continue to watch" section

### ISSUE THREAD

**Issue by R1D3R175** [Bonfra04/Stronzflix#43]
How to reproduce:
1. Download an episode
2. Open it, thus it gets marked as being watched
3. Go back to the "Downloaded" source
4. Delete the episode

If you click on the title in thew "Continue" to watch section the app will crash

**Comment by Bonfra04** [comment]
Known issue in 0.2.4 changelog, thanks for creating the issue
