### ISSUE TITLE
Add site favicon to distinguish between various sources in "Continue to watch"

### ISSUE THREAD

**Issue by R1D3R175** [Bonfra04/Stronzflix#44]
![image](https://github.com/user-attachments/assets/e82c4477-41d8-4868-9c54-a02430b08061)
On the left the source is StreamingCommunity, on the right is downloaded.

I suggest adding the website favicon in the bottom right corner of the card and the download icon for the downloaded source.

To avoid contrast problems I also suggest placing it inside something like a button
![image](https://github.com/user-attachments/assets/c7e1ec14-7faa-452a-9a6e-82a372fcd832)

**Comment by Bonfra04** [comment]
Added in 3da6696ec7320da8dfb61bb7db1be38eebc98029.
