### ISSUE TITLE
Make very long text automatically scroll or wrap

### ISSUE THREAD

**Issue by codesimo** [Bonfra04/Stronzflix#51]

**Comment by Bonfra04** [comment]
Please be more specific. maybe with some screenshots or specify the part of the application

**Comment by codesimo** [comment]
You should have told me earlier, for example when on discord you told me to open this issue :).

I think you were referring to the title of episodes/movies when searching, particularly on anime, which if too long do not allow you to understand either if it is “sub-ita” or the entire title itself.

**Comment by Bonfra04** [comment]
Hm, i don't think so. In that case it would be a duplicate of #18
