### ISSUE TITLE
Support DLNA TVs

### ISSUE THREAD

**Issue by R1D3R175** [Bonfra04/Stronzflix#54]
Currently, only Chromecast is supported. Many smart TVs use DLNA. I propose the implementation of the following.

**Comment by Bonfra04** [comment]
Support started with 542c113daafe2874d07c1e613f6c01433502d4ee. Sadly if the web server blocks TVs by user-agent the playback will not work.
Still, it works on Kodi and other TVs with a non-blocked user agent.
