### ISSUE TITLE
Media preview doesn't always render for Windows SMTC

### ISSUE THREAD

**Issue by Bonfra04** [Bonfra04/Stronzflix#7]
###  Problem 
The library used for SMTC, [smt_windows](https://github.com/KRTirtho/smtc_windows), only allows for URL to be passed trough the Rust wrapper and it generates itself the random access stream to feed the windows API. If the provided URL is of an image not in the correct format it will not render.

### Proposed Solution
Fork the library and add a method that takes a byte array as a parameter so any needed conversion can be done dart-side.

### Rejected Solutions
Save the image locally, convert it, and pass a new URL to that image

**Comment by Bonfra04** [comment]
Fixed in [1e4630a16ea17e81161a65e7737887ae10e30222](https://github.com/Bonfra04/Stronzflix/commit/208eea6ebe623384504543a2ce55e0c584158172)

**Comment by codesimo** [comment]
It might make sense to move ownership of the fork https://github.com/Bonfra04/smtc_windows to StronzLabs
